# rbt_cfg.toml

[game_cfg]
# 电控发送优先级大于自己设置的优先级
# 如果设置出现错误，会有 log 警告
enemy_fraction = "blue"
# enemy_fraction = "red"

[logger_cfg]
console_log_filter = "info,auto_aim_rust=debug,ort=warn"
file_log_filter = "info,auto_aim_rust=debug,ort=info"
console_log_enable = true
file_log_enable = true

[general_cfg]
img_dbg = false
bullet_speed = 24.0

[detector_cfg]
armor_detect_model_path = "./model/armor/best_fp16_norm.onnx"
armor_detect_engine_path = "./model/armor"
buff_detect_model_path = "./model/buff/buff.onnx"
camera_img_width = 1280
camera_img_height = 720
infer_img_width = 640
infer_img_height = 360
infer_full_height = 480
confidence_threshold = 0.8
ort_ep = "OpenVINO"

[cam_cfg]
cam_k = [1600.0, 0.0, 320.0, 0.0, 1705.7, 192.0, 0.0, 0.0, 1.0]

