[workspace]
members = ["lib", "bin/auto_aim", "bin/auto_aim_async", "bin/sqpnp_benchmark"]
default-members = ["lib"]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["Lu Zhongjin <luzhongjin365@gmail.com>"]
license = "MIT"

[profile.release]
opt-level = 3
