[workspace]
members = [
    "lib",
    "app/auto_aim_async",
    "app/ippe_benchmark",
    "app/single_frame_dev",
    "app/comm_test"
]
default-members = ["lib"]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["Lu Zhongjin <luzhongjin365@gmail.com>"]
license = "MIT"

[profile.release]
opt-level = 3

[workspace.dependencies]
# base
nalgebra = "0.35.0"
imageproc = "0.27.0"
image = "0.25.10"
tinympc-rs = { git = "https://github.com/3SE-Competitive-Robotics-Team/tinympc-rs", branch = "codex/zhongjin/nalgebra-0-35" }

# for infer
ndarray = "0.17.2"
ort = { version = "2.0.0-rc.12", features = ["tensorrt", "openvino", "coreml"] }

# error handle
thiserror = "2.0.18"

# logger
log = "0.4.32"
logforth = { version = "0.30.1", features = ["starter-log", "append-file", "append-async", "layout-text", "filter-rustlog"] }
logforth-append-file = "0.4.0"
logforth-append-async = "0.4.0"
rerun = "0.33.0"

# cfg
toml = "1.1.2"
lazy_static = "1.5.0"
serde = { version = "1.0.228", features = ["derive"] }

# framework
tokio = { version = "1.52.3", features = ["full"] }
tokio-serial = "5.4.5"
jiff = { version = "0.2.28", default-features = false, features = ["std", "tz-system"] }
notify = "8.2.0"
crossbeam-queue = "0.3.12"

# enum reflect
strum = {version = "0.28.0", features = ["derive"]}
