[package]
name = "ippe_benchmark"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lib = { path = "../../lib" }
nalgebra = {workspace = true}
tracing = {workspace = true}
rerun = {workspace = true}
